name: Generate SDK
on:
  workflow_dispatch:
    inputs:
      generator:
        type: choice
        description: Which generator config should be used to run SDK
        required: true
        options:
          - angular-generator-config.json
          - react-generator-config.json
        default: angular-generator-config.json

jobs:
  run-generator:
    name: Generate SDK
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit
      # and push the added or changed files to the repository.
      contents: write

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Build SDK generator
        run: |
          docker build . \
          --file generator/Dockerfile \
          --tag openapi-generator:latest

      - name: Generate SDK
        run: |
          echo "generator=${{ github.event.inputs.generator }}" \
          &&
          docker run --rm \
          --volume $GITHUB_WORKSPACE/sdk:/local/ \
          --volume $GITHUB_WORKSPACE/generator/${{ github.event.inputs.generator }}:/sdk/${{ github.event.inputs.generator }} \
          openapi-generator:latest generate \
          --input-spec ${{ secrets.URL_TO_OPENAPI_SPEC }} \
          --config /sdk/${{ github.event.inputs.generator }} \
          --git-user-id ${{ github.actor }} \
          --git-repo-id ${{ github.event.repository.name }} \

      - name: Check SDK version
        id: check_sdk_version
        run: |
           echo "sdk_version=$(cat sdk/package.json | grep -oP '(?<="version": ")([\d\.]+)(?=")')" >> $GITHUB_OUTPUT

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
            push_options: '--force'
            commit_message: Update SDK
            branch: develop
            tagging_message: ${{ steps.check_sdk_version.outputs.sdk_version }}
